Repository onecompiler/cheatsheets, pull requests merged in 2022-10, with the labels that each got.

#50 Added information about classes
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest

#69 Update python.md [Try Except]
  python.md
Labels: hacktoberfest-accepted, hacktoberfest

#64 Added Pre Tag in HTML tags
  html.md
Labels: hacktoberfest-accepted, hacktoberfest

#53 added uncommon DNS record types & corrected spelling
  dns.md
Labels: hacktoberfest

#73 Updated `GIT` cheetsheet
  git.md
Labels: hacktoberfest

#75 Update git.md
  git.md
Labels: hacktoberfest

#88 Updated go.md
  go.md
Labels: hacktoberfest-accepted, hacktoberfest

#91 various typo and grammar fixes to help readability
  css.md
Labels: hacktoberfest-accepted, hacktoberfest

#90 Updated hooks in reactjs.md
  reactjs.md
Labels: hacktoberfest-accepted, hacktoberfest

#84 Added Solidity cheatsheet file
  solidity.md
Labels: hacktoberfest-accepted, hacktoberfest

#83 Added Flutter Cheatsheet resources.
  flutter.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#58 Added information about javaScript DOM
  javascript.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#80 Update android-versions.md
  android-versions.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#78 Create SQL.md
  SQL.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#77 added variable to the CSS cheatsheet
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#85 Updated Hashset Hashmap and Arrraylist
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#97 the changes are done
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#98 Added more power to the "CSS cheatsheet" selector section
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#114 Updated iphone-screen-resolutions.md
  iphone-screen-resolutions.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#109 Added Animations and Transitions
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#99 Added units to the CSS cheatsheet
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#121 UPDATED SQL JOINS
  sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#120 Added Media queries section to the CSS cheatsheet
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#126 Update heroku.md
  heroku.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#106 Added string functions and Dynamic Memory Allocation
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#119 Adds information about bits/stdc++.h file
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#107 Added MySQLi Functions
  php.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#130 Added the Kubernetes cheat sheet as part of Hacktoberfest- Issue #94
  kubernetes.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#132 Updated Linux Cheatsheet
  linux.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#133 Added audio and video tag in HTML Tag table
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#150 Changed Android R name
  android-versions.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#151 Corrected the title in Conditional statements
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#152 added JS 2019 details
  javascript-versions.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#153 Added boolean Literal, graphics.h, greater function in sorting
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#157 Update java.md
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#144 Create netlify.md
  netlify.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#154 Added some escape sequences
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#161 Update pwd.md
  pwd.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#163 rust.md
  rust.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#182 Update cd.md
  cd.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#180 Update adb.md
  adb.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#179 Update adb.md
  adb.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#176 Created Vyper Cheatsheet
  vyper.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#167 minor typo fixes
  bash.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#199 Updated cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#203 html-lazy-load-feature
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#201 Added jQuery.md
  jQuery.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#165 Added the Rust cheatsheet as part of Hacktoberfest - Issue #95
  rust.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#175 Added semantic tags of html
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#194 Update java-strings.md
  java-strings.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#185 Added Header files Information in c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#190 Update cat.md
  cat.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#189 Update cat.md
  cat.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#197 Updated cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#223 (fix) wrong numberings in some files
  cat.md
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#226 Update java-primitive-data-types.md
  java-primitive-data-types.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#229 (new) HTTP status code cheatsheet
  http-staus-codes.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#205 Created Markdown.md
  markdown.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#227 Python datatype
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#220 Update dotenv.md
  dotenv.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#240 Update javascript-versions.md
  javascript-versions.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#239 Updated dictionary operations of python.md
  cpp.md
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#242 Constructor java
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#246 Update java.md
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#248 Update angular.md
  angular.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#249 Update c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#255 Update python.md
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#256 Updated cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#257 Updated c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#259 Updated c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#261 Update cpp.md in variable naming convention
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#264 Update cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#265 Update css.md
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#269 Update java.md
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#273 Updated string functions of c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#275 Adding syntax of ternary operator in cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#278 Adds Source Tag
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#279 Adds <big> tag
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#284 added .camelCase() lodash method
  lodash.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#286 added a new option in 'echo' command
  echo.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#258 Updated c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#293 added String in cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#290 Added a method in c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#288 added scope resolution operator in Operators section in c++
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#295 Adding cpp keywords in cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#307 Removes bits/stdc++.h from header files
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#306 Adds range in input
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#305 Adds SVG element
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#294 Added Date, file, some mysqli extensions, superglobals and fixed some typos
  php.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#303 Adding cursor topic in mysql.md
  my-sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#312 Added string functions
  csharp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#333 Corrected Polymorphism example and added Inheritance example
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#329 Updated triggers in mysql.md
  mysql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#328 Added some methods in sorting and updated info of some headers
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#348 Update sql.md
  sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#347 Update node cheat sheet
  nodejs.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#340 Adds Progress Tag
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#339 Adds Kbd Tag
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#341 Update python.md
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#337 Updated missing relative units in css.md
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#419 Added a bcryptjs.md which consist of introduction of a popular npm package bcrpytjs.
  bcryptjs.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#418 Updated collections in java.md
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#414 Update cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#381 Update java.md for minor changes
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#382 Documentation for various sql commands in Mysql.md
  mysql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#407 Azure Cheatsheet
  Azure_Fundamentals.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#358 Adding some useful vector functions in C++ cheatsheet
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#421 Updated missing string function in c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#361 Updated cpp.md with missing header files
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#357 add variable declaration through export
  bash.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#363 `curl`:fix a small typo
  curl.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#377 added-references-cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#387 Adds <bdo> tag
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#390 updatedInputElements.html
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#426 Updated a missing input tag from html.md
  html.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#439 Update java-strings.md
  java-strings.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#435 Added few more escape sequences
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#430 Added 'Destructuring Arrays' section to Javascript cheatsheet
  javascript.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#428 Updated a missing constraint in sql.md
  cpp.md
  sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#445 Update csharp.md
  csharp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#427 Updated missing constraint in sql.md
  sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#456 Update angular.md
  angular.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#463 Added math and random functions in C cheatsheet
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#462 Update python.md
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#466 Update css.md
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#467 Update markdown.md
  markdown.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#468 Update c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#470 Update java.md
  java.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#471 fflush
  c.md
  sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#469 Created typescript.md
  typescript.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#484 Updated data search-engins.md
  search-engins.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#476 Added `upstream` command
  git.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#485 Added Commands for Managing Database User DCL Commands
  sql.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#490 Added Pseudo-class in CSS with example
  css.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#497 CristinaEU1
  mongodb.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#495 Update bash.md
  bash.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#503 updated c.md
  c.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#501 Added Figma.md
  figma.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#505 Update cpp.md
  cpp.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#504 Created windows-shortcuts.md file
  windows-shortcuts.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#506 Update linux.md
  linux.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#508 Added information about how to create a new set.
  python.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22

#511 docs- required changes in the commit and stash section
  git.md
Labels: hacktoberfest-accepted, hacktoberfest, hacktoberfest22
